// Builds the search index the API answers from.
//
//   node rag/ingest.mjs              embed everything in ../sources and write the index (needs the API key)
//   node rag/ingest.mjs --dry-run    show what would be indexed and the estimated cost; no API calls
//   node rag/ingest.mjs --mock       build a fake index for testing without a key (never deploy it)
//
// Sources are listed in Jeju_4-3/sources/manifest.json. Each document is a UTF-8 .txt file where
// pages are separated either by "[[page N]]" lines or by form feeds (what `pdftotext` produces).
// Output: netlify/functions/ask/data/index.mjs

import fs from 'node:fs';
import path from 'node:path';
import { loadEnv, REPO_ROOT, ENV_FILE } from './env.mjs';

const args = new Set(process.argv.slice(2));
if (args.has('--mock')) process.env.MOCK_OPENAI = '1';
const dryRun = args.has('--dry-run');
loadEnv();

const { embed, quantise, CONFIG, isMock, hasHangul } = await import('../netlify/functions/ask/lib.mjs');

const SOURCES = path.resolve(process.env.SOURCES_DIR || path.join(REPO_ROOT, '..', 'sources'));
const OUT = path.join(REPO_ROOT, 'netlify', 'functions', 'ask', 'data', 'index.mjs');
const TARGET = { en: 1100, ko: 550 }; // characters per chunk

const manifest = JSON.parse(fs.readFileSync(path.join(SOURCES, 'manifest.json'), 'utf8'));
const docs = {};
const chunks = [];

for (const d of manifest.documents) {
  if (d.index === false) continue;
  const raw = fs.readFileSync(path.join(SOURCES, d.file), 'utf8');
  const lang = d.language || (hasHangul(raw) ? 'ko' : 'en');
  docs[d.id] = {
    title: d.title,
    type: d.type,
    trust: d.trust || 'secondary',
    language: lang,
    url: (String(d.source_url || '').match(/^https?:\/\/\S+/) || [null])[0],
    author: d.author || null,
    date: d.date || null,
  };
  const before = chunks.length;
  for (const { page, text } of pages(raw)) {
    for (const t of chunkText(clean(text), TARGET[lang] || TARGET.en)) chunks.push({ d: d.id, p: page, t });
  }
  console.log(`  ${d.id.padEnd(14)} ${String(chunks.length - before).padStart(5)} chunks  ${d.title.slice(0, 60)}`);
}

const chars = chunks.reduce((s, c) => s + c.t.length + (docs[c.d].title.length + 1), 0);
const estTokens = Math.round(chunks.reduce((s, c) => s + (hasHangul(c.t) ? c.t.length / 1.3 : c.t.length / 4), 0));
console.log(`\n${Object.keys(docs).length} documents, ${chunks.length} chunks, ${chars.toLocaleString()} characters`);
console.log(`Embedding ≈ ${estTokens.toLocaleString()} tokens with ${CONFIG.embedModel()} (about $${(estTokens / 1e6 * 0.02).toFixed(3)} at $0.02 per million)`);

if (dryRun) process.exit(0);
if (!isMock() && !process.env.OPENAI_API_KEY) {
  console.error(`\nNo OPENAI_API_KEY. Put it in ${ENV_FILE} as a line:\n  OPENAI_API_KEY=sk-...\n`);
  process.exit(1);
}

console.log(isMock() ? '\nMOCK mode: fake embeddings, for testing only.' : '\nEmbedding…');
const vecs = await embed(chunks.map((c) => `${docs[c.d].title}\n${c.t}`));
const q = quantise(vecs);
const index = {
  version: 1,
  built: new Date().toISOString(),
  embed_model: isMock() ? 'mock' : CONFIG.embedModel(),
  dims: q.dims,
  docs,
  chunks,
  vectors: q.vectors,
  scales: q.scales,
};
fs.writeFileSync(OUT, `// Generated by rag/ingest.mjs on ${index.built}. Do not edit by hand.\nexport default ${JSON.stringify(index)};\n`);
console.log(`Wrote ${path.relative(REPO_ROOT, OUT)} (${(fs.statSync(OUT).size / 1e6).toFixed(1)} MB)`);

// ───────────────────────── helpers ─────────────────────────

function pages(raw) {
  if (/\[\[page \d+\]\]/.test(raw)) {
    const out = [];
    const re = /\[\[page (\d+)\]\]\n?/g;
    let m, last = null;
    while ((m = re.exec(raw))) {
      if (last) out.push({ page: last.page, text: raw.slice(last.end, m.index) });
      last = { page: Number(m[1]), end: re.lastIndex };
    }
    if (last) out.push({ page: last.page, text: raw.slice(last.end) });
    return out;
  }
  if (raw.includes('\f')) return raw.split('\f').map((text, i) => ({ page: i + 1, text }));
  return [{ page: null, text: raw }];
}

function clean(s) {
  return s
    .replace(/([a-z])-\n([a-z])/g, '$1$2')      // re-join words hyphenated across lines
    .replace(/[ \t]*\n[ \t]*/g, ' ')            // PDF line breaks → spaces
    .replace(/\s{2,}/g, ' ')
    .trim();
}

function chunkText(text, target) {
  if (!text) return [];
  const sentences = text.split(/(?<=[.!?。])\s+/).flatMap((s) => splitLong(s, target));
  const out = [];
  let cur = [];
  let len = 0;
  for (const s of sentences) {
    if (len + s.length > target && cur.length) {
      out.push(cur.join(' '));
      const carry = cur[cur.length - 1];                 // one sentence of overlap
      cur = carry.length < target / 3 ? [carry] : [];
      len = cur.reduce((a, x) => a + x.length + 1, 0);
    }
    cur.push(s);
    len += s.length + 1;
  }
  if (cur.length) out.push(cur.join(' '));
  return out.filter((c) => c.replace(/\W/g, '').length > 40);
}

function splitLong(s, target) {
  if (s.length <= target * 1.5) return [s];
  const parts = [];
  let rest = s;
  while (rest.length > target) {
    let cut = rest.lastIndexOf(' ', target);
    if (cut < target / 2) cut = target;
    parts.push(rest.slice(0, cut));
    rest = rest.slice(cut).trim();
  }
  if (rest) parts.push(rest);
  return parts;
}
